version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.21.0
  - dependency-name: eslint-plugin-testing-library
    versions:
    - 4.0.0
  - dependency-name: react-use
    versions:
    - 17.0.1
    - 17.2.3
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.6
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: stylelint-config-recommended
    versions:
    - 4.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.2
  - dependency-name: react-scripts
    versions:
    - 4.0.2
    - 4.0.3
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
  - dependency-name: "@types/ramda"
    versions:
    - 0.27.37
  - dependency-name: lint-staged
    versions:
    - 10.5.4
  - dependency-name: yup
    versions:
    - 0.32.8
